### ISSUE TITLE
Netplan function update - Support auto-config static ip & remove dhcp

### ISSUE THREAD

**Issue by hezhijie0327** [hezhijie0327/AutoDeploy#13]
https://github.com/hezhijie0327/AutoDeploy/blob/f7395560e1ca35d581f3de7ca0d71fa22934f95f/Ubuntu.sh#L523-L550

**Comment by hezhijie0327** [comment]
```
network:
  version: 2
  renderer: networkd
  ethernets:
    enp3s0:
      addresses:
        - 10.10.10.2/24
      nameservers:
        search: [mydomain, otherdomain]
        addresses: [10.10.10.1, 1.1.1.1]
      routes: 
        - to: default
          via: 10.10.10.1
```
